version: "3"
services:
  i2p:
    image: chrisbensch/docker-i2p:latest
    container_name: i2p
    ports:
      - '7654:7654'
      - '7656:7656'
      - '7657:7657'
      - '4444:4444'
      - '4445:4445'
      - '6668:6668'
      - '6669:6669'
    restart: always
